name: Github Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Trigged by event ${{ github.event_name }}"
          echo "The name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files"
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    needs: Build
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - run: |
          echo "Load Testing..."
          sleep 15
  
